title: "runnチュートリアル"
summary: "APIシナリオテストツールでもある runn の使い方をステップバイステップで理解していくチュートリアルをまとめたZenn bookです"
topics: ["e2e","automation","api","チュートリアル","runn"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - about
  - install
  - hello-world
  - curl
  - desc
  - vars
  - env-vars
  - test
  - previous
  - ordered-map
  - bind
  - loop
  - include
  - include-vars
  - included
  - json
  - template
  - dump
  - openapi
  - exec
  - db-runner
  - cdp-runner
  - github-actions
  - multiparti-form-data
  - compilation
  - coverage
  - trace
  - appendix
