name: textlint
on: [pull_request]
jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          reporter: github-pr-review
          level: warning
          textlint_flags: "articles/**"
          filter_mode: "diff_context"
